apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-ingress
  namespace: {SERVICE_NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  # No TLS for this test
  rules:
    - host: {DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: {SERVICE_PORT}