apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {CERT_ISSUER}
spec:
  acme:
    server: "{CERT_URL}" # TBD: for testing use https://acme-staging-v02.api.letsencrypt.org/directory
    email: {CERT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-privatekey
    solvers:
      - http01:
          ingress:
            class: nginx
