apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {CERT_ISSUER}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory # TBD: use staging or prod URL
    email: {CERT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-privatekey
    solvers:
      - http01:
          ingress:
            class: nginx
