controller:
  enabled: true
  service:
    type: LoadBalancer
    externalTrafficPolicy: {EXTERNAL_TRAFFIC_POLICY}
  # Default configuration for nginx controller
  config: {}
  # No SSL passthrough by default
  # No tolerations by default

defaultBackend:
  enabled: true
  # Commenting out this section until certs are issued
  # extraArgs:
  #   default-ssl-certificate: default/tls-secret # TBD: namespace/secret-name for valid TLS certificate
