config:
  clientID: {OAUTH_CLIENT_ID}
  clientSecret: {OAUTH_CLIENT_SECRET}
  cookieSecret: {OAUTH_COOKIE_SECRET}
  githubOrg: {GITHUB_ORG} 

extraArgs:
  provider: {OAUTH_PROVIDER}
  # github-org: {GITHUB_ORG} seems to be ignored
  whitelist-domain: "{DOMAIN}"
  cookie-domain: "{DOMAIN}"
  pass-basic-auth: "true"
  pass-user-headers: "true"

ingress:
  enabled: false                                 # ingress handled separately (app-ingress + oauth ingress)
