apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {SERVICE_NAMESPACE}
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {SERVICE_NAMESPACE}
  labels:
    app: web
spec:
  ports:
  - port: {SERVICE_PORT}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: web
