name: Post Feedback Link

on:
  pull_request:
    types: [opened, reopened]

jobs:
  survey-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment with survey link
        uses: octodemo/Copilot-Value-Estimate/action.yml  # or wherever your action.yml is
        with:
          base-url: https://www.gvm-chart.com/copilot/surveys/new
