name: estimate copilot time savings

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  post-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Post PR feedback link
        uses: octodemo/Copilot-Value-Estimate@v1
        with:
          base-url: https://www.gvm-chart.com/copilot/surveys/new
