name: PR Survey

on:
  pull_request:
    types: [opened]  # Trigger when PRs are opened

jobs:
  post-survey:
    runs-on: ubuntu-latest
    steps:
      # Use the reusable PR Survey Comment action
      - name: Post Survey Comment
        uses: MattG57/Copilot-Value-Estimate
        with:
          base-url: 'https://www.gvm-chart.com/copilot/surveys/new'
          # Optional: Customize the message
          custom-message: '📊 Thank you for your contribution! We would love your feedback on this PR experience.'
          # Optional: Add additional query parameters
          additional-params: '{"team":"engineering","source":"github-action"}'

  # You can combine this with other PR workflows
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment
        # Your setup steps here
        run: echo "Setting up test environment"
      
      - name: Run tests
        # Your test command here
        run: echo "Running tests"
