name: PR Survey Comment
on:
  pull_request:
    types: [opened, reopened]  # Specifically define when this should trigger

jobs:
  post-survey:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Post PR feedback comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ github.token }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            📊 Thank you for your contribution! We would love your feedback on this PR experience.
            
            [Click to give feedback](https://www.gvm-chart.com/copilot/surveys/new?author=${{ github.event.pull_request.user.login }}&repo=${{ github.repository }}&prno=${{ github.event.pull_request.number }}&team=engineering&source=github-action)
