name: Post Feedback Link

on:
  pull_request:
    types: [opened, reopened]

jobs:
  call-post-survey:
    uses: octodemo/Copilot-Value-Estimate/.github/workflows/post-feedback-link.yml@v1
    with:
      base-url: https://www.gvm-chart.com/copilot/surveys/new
