apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-retain
  labels:
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    helm.sh/resource-policy: keep
provisioner: {{ .Values.storageProvisioner | default "pd.csi.storage.gke.io" }}
parameters:
  type: {{ .Values.storageType | default "pd-ssd" }}
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
