apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  labels:
    app: mongodb
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - "136.28.117.64/32"  # Replace with your actual IP
  externalTrafficPolicy: Local
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongo-for-aks  # Match this to your Helm release name
